
from fastapi import APIRouter

from models.user_model import User

router = APIRouter()


@router.post("/register_user", tags=["Users"])
async def register_user(user: User):
    return User(
        userid=1,  # Placeholder user ID, in a real application this would be generated by the database
        email=user.email,
        password=user.password,
        full_name=user.full_name,
        access_token="placeholder_access_token",
        refresh_token="placeholder_refresh_token",
    )