services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    vaolumes:
      - db_data:/var/lib/postgresql/data

volumes:
  pgdata: